name: six_pos
description: A new Flutter application.
publish_to: 'none' #
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  connectivity_plus: ^6.1.4
  firebase_core: ^3.15.2
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^17.1.0
  path_provider: ^2.1.5
  image_picker: ^1.1.0
  fl_chart: ^0.70.2
  get: ^4.6.6
  flutter_switch: ^0.3.2
  timezone: ^0.9.0
  file_picker: ^10.2.0
  barcode_widget: ^2.0.4
  barcode_scan2: ^4.5.1

  permission_handler: ^11.3.1
  flutter_downloader: ^1.12.0
  shimmer: ^3.0.0
  url_launcher: ^6.2.6
  flutter_spinkit: ^5.2.1
  typed_data: ^1.3.2
  http_parser: ^4.1.2
  path: ^1.9.0
  http: ^1.3.0
  dropdown_search: ^5.0.6
  just_the_tooltip: ^0.0.12
  print_bluetooth_thermal: ^1.1.5
  esc_pos_utils_plus: ^2.0.3
  flutter_svg: ^2.0.17
  buttons_tabbar: ^1.3.12
  syncfusion_flutter_datepicker: ^28.1.41
  dropdown_button2: ^2.3.9
  dotted_border: ^2.1.0
  dotted_line: ^3.2.3
  screenshot: ^3.0.0
  image: ^4.5.2
  readmore: ^3.0.0
  skeletonizer: 2.1.0+1
  another_xlider: ^3.0.2






dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/
    - assets/svg/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/font/Ubuntu-Regular.ttf
          weight: 400
        - asset: assets/font/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/font/Ubuntu-Bold.ttf
          weight: 600
        - asset: assets/font/Ubuntu-Light.ttf
          weight: 300